server:
   port: 8083
# MySql #
# spring.jpa.hibernate.ddl-auto=update
spring:
  datasource: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/db_ms_clientes
#    url: jdbc:mysql://mysql-dev-ms:3306/db_ms_clientes
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
   show-sql: true
   properties:
     hibernate:
       dialect :  org.hibernate.dialect.MySQLDialect