apiVersion: v1
kind: Service
metadata:                     
  name: ms-negocio-gestion-productos-service
  labels:                   
    app: ms-negocio-gestion-productos
spec:                         
  type: LoadBalancer 
  selector:
    app: ms-negocio-gestion-productos
  ports:
  - name: http
    port: 8082
    targetPort: 8082