server:
   port: 8083
# MySql #
# spring.jpa.hibernate.ddl-auto=update
spring:
  datasource: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/db_ms_clientes
#    url: jdbc:mysql://mysql-dev-ms:3306/db_ms_clientes
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
   show-sql: true
   properties:
     hibernate:
       dialect :  org.hibernate.dialect.MySQLDialect