server:
   port: 8082

spring:
  application:
    name: ms-negocio-gestion-productos

  jpa:
     show-sql: true
     hibernate:
       ddl-auto: create
  datasource:
    url: jdbc:mysql://${DB_SERVICE:localhost:3306}/db_curs-000189_productos?createDatabaseIfNotExist=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
