server:
  port: 8888

spring:
  application:
    name: ms-infraestructure-server-config

#Configuracion Local
  profiles:
    active: native
  cloud:
    config:
      server: 
        native:
          searchLocations: file:///D:/AmbDesarrollo/Cursos/InTraining/CURS-000189-ARQMSSpring/ms-infraestructure-data-config
# Acuator
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true