server:
   port: 8084
   
# MySql #
spring:
  jpa: 
    hibernate: 
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
       dialect :  org.hibernate.dialect.MySQLDialect
  datasource: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/db_ms_productos?createDatabaseIfNotExist=true&useSSL=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  