apiVersion: v1
kind: Secret
metadata:
  name: github-user-credentials-secret
type: Opaque
stringData:
  userPassword: "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"
  userName: "arisoft1@gmail.com"
# YXJpc29mdDFAZ21haWwuY29t
# Z2hwX09ZMGQxVzdxSXNqUVM4aUVKb2VScFRLT2lRdlB0bDIzemZEbg==