apiVersion: v1
kind: Service
metadata:                     
  name: ms-negocio-gestion-pedidos-service
  labels:                   
    app: ms-negocio-gestion-pedidos
spec:                         
#  type: LoadBalancer
  type: NodePort 
  selector:
    app: ms-negocio-gestion-pedidos
  ports:
  - name: http
    port: 8084
    targetPort: 8084