apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-negocio-gestion-pedidos-deployment
  labels:                     
    app: ms-negocio-gestion-pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-negocio-gestion-pedidos
  template:
    metadata:
      labels:
        app: ms-negocio-gestion-pedidos
    spec:
      containers:
      - name: ms-negocio-gestion-pedidos
        image: 179286536309.dkr.ecr.sa-east-1.amazonaws.com/ms-negocio-gestion-pedidos:0.0.1
 #       imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8084
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
        env:
#        - name: SPRING_DATASOURCE_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: mysql-root-secret
#              key: username
#        - name: SPRING_DATASOURCE_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mysql-root-secret
#              key: password
#        - name: SPRING_DATASOURCE_URL
#          valueFrom:
#            secretKeyRef:
#              name: mysql-dbs-urls-secret
#              key: ms_productos_db_url
        - name: MS_SERVER_CONFIG
          valueFrom: 
            secretKeyRef:
              name: mysql-ms-server-config-urls-secret
              key: ms_server-config_url