name: ms-demo-stack
services:

  ms-demo-dev1:
    container_name: ms-demo-dev1
    image: ms-demo:latest
    restart: on-failure
#    build: .
    ports:
      - "8082:8082"
  ms-demo-dev2:
    container_name: ms-demo-dev2
    image: ms-demo:latest
    restart: on-failure
#    build: .
    ports:
      - "8083:8082"      

