apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-administracion-server-admin-deployment
  labels:                     
    app: ms-administracion-server-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-administracion-server-admin
  template:
    metadata:
      labels:
        app: ms-administracion-server-admin
    spec:
      containers:
      - name: ms-administracion-server-admin
        image: 179286536309.dkr.ecr.sa-east-1.amazonaws.com/ms-administracion-server-admin:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8890
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:                     
  name: ms-administracion-server-admin-service
  labels:                   
    app: ms-administracion-server-admin
spec:                         
  type: LoadBalancer 
  selector:
    app: ms-administracion-server-admin
  ports:
  - name: http
    port: 8890
    targetPort: 8890