apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql-v2-deployment
  labels:
    app: ms-demo-v2-app
spec:
  selector:
    matchLabels:
      name: db-mysql-v2-pod
      app: ms-demo-v2-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: db-mysql-v2-pod
      labels:
        name: db-mysql-v2-pod
        app: ms-demo-v2-app
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: rootPassword
#        - name: MYSQL_DATABASE
#          valueFrom:
#            secretKeyRef:
#              name: mysql-db-url
#              key: database
#        - name: MYSQL_USER
#          valueFrom:
#            secretKeyRef:
#              name: mysql-user-credentials
#              key: username
#        - name: MYSQL_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mysql-user-credentials
#              key: password
        ports:
        - containerPort: 3306     
          name: mysql
        # volumeMounts:
        # - name: mysql-persistent-storage
        #   mountPath: /var/lib/mysql
        # volumes:
        # - name: mysql-persistent-storage
        # persistentVolumeClaim:
        #   claimName: mysql-pv-claim