server:
   port: 8081

spring:
#  application:
#    name: ms-negocio-gestion-cliente
# MySQL
  jpa:
     show-sql: true
 #    hibernate:
 #      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/db_curs-000189_clientes?createDatabaseIfNotExist=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


# Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port:8081}

# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka


# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always    