apiVersion: v1
kind: Service
metadata:
  name: ms-demo-v2-service
  labels:
    app: ms-demo-v2
spec:
  type: LoadBalancer
  selector:
    app: ms-demo-v2
  ports:
  - name: http
    port: 8084
    targetPort: 8084