apiVersion: v1
kind: Service
metadata:                     
  name: ms-administracion-api-gateway-service
  labels:                   
    app: ms-administracion-api-gateway
spec:                         
  type: LoadBalancer 
  selector:
    app: ms-administracion-api-gateway
  ports:
  - name: http
    port: 8887
    targetPort: 8887