apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-demo-v1-deployment
  labels:
    app: ms-demo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-demo-v1
  template:
    metadata:
      labels:
        app: ms-demo-v1
    spec:
      containers:
      - name: ms-demo-v1
        image: 179286536309.dkr.ecr.sa-east-1.amazonaws.com/ms-demo-v1:0.0.1
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8082
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m